USE master
GO 
CREATE  DATABASE QuanLyKhachSan

GO
USE QuanLyKhachSan

GO 
CREATE TABLE NhanVien
(
	MaNV VARCHAR(10) PRIMARY KEY,
	TenNV NVARCHAR(30),
	GioiTinh NVARCHAR(5) CHECK (GioiTinh IN (N'Nam',N'Nữ')),
	NgaySinh	DATE,
	DiaChi NVARCHAR(50),
	CMND   VARCHAR(15),
	SDT   VARCHAR(15)
)

GO 
CREATE TABLE KhachHang
(
	MaKH VARCHAR(10) PRIMARY KEY,
	TenKH NVARCHAR(30),
	GioiTinh NVARCHAR(5),
	NamSinh INT ,
	DiaChi NVARCHAR(50),
	CMND   VarCHAR(15),
	SDT   VarCHAR(12)
)

GO 
CREATE TABLE LoaiPhong
(
	MaLoaiPhong VARCHAR(10) PRIMARY KEY,
	LoaiPhong NVARCHAR(50)
)

GO 
CREATE TABLE Phong(
	MaPhong VARCHAR(10) PRIMARY KEY,
	TenPhong NVARCHAR(50),
	MaLoaiPhong VARCHAR(10),
	TrangThai NVARCHAR(50),
	FOREIGN KEY(MaLoaiPhong) REFERENCES dbo.LoaiPhong(MaLoaiPhong)
)

GO 
CREATE TABLE PhieuDangKy(
	MaPhieuDK VARCHAR(10) PRIMARY KEY,
	MaKH VARCHAR(10),
	MaPhong VARCHAR(10),
	MaNV VARCHAR(10),
	NgayLap DATE ,
	TienCoc INT ,
	FOREIGN KEY(MaKH) REFERENCES dbo.KhachHang(MaKH),
	FOREIGN KEY(MaNV) REFERENCES dbo.NhanVien(MaNV),
	FOREIGN KEY(MaPhong) REFERENCES dbo.Phong(MaPhong)
)

GO 
CREATE TABLE PhieuDichVu(
	MaPhieuDV VARCHAR(10) PRIMARY KEY,
	TenDV NVARCHAR(50),
	MaPhieuDK VARCHAR(10),
	Gia INT ,
	FOREIGN KEY(MaPhieuDK) REFERENCES dbo.PhieuDangKy(MaPhieuDK)
)

GO 
CREATE TABLE HoaDon(
	MaHD VARCHAR(10) PRIMARY KEY,
	MaPhieuDK VARCHAR(10),
	MaNV VARCHAR(10),
	NgayThanhToan DATE,
	TongTien INT ,

	FOREIGN KEY(MaPhieuDK) REFERENCES dbo.PhieuDangKy(MaPhieuDK),
	FOREIGN KEY(MaNV) REFERENCES dbo.NhanVien(MaNV)
)

ALTER TABLE dbo.NhanVien ADD Luong Int 
GO

